### ISSUE TITLE
[BUG] Booleans are treated as numbers instead of strings.

### ISSUE THREAD

**Issue by gradylink** [NateXS/Scratch-3DS#213]
### Describe the crash or bug

Pretty much just the title so like when you set a variable to the value of a boolean operation it shows as `1` or `0` instead of `true` or `false`.

### Scratch Project

https://files.catbox.moe/4cjsrp.sb3 (this requires the custom extensions branch and the bitwise custom extension) but I pretty much explained how to make a simple version in the first section.

### Screenshots

<img width="413" height="181" alt="Image" src="https://github.com/user-attachments/assets/325b0ef8-d07e-47ce-ae28-84587b3eb2a8" />

<img width="324" height="171" alt="Image" src="https://github.com/user-attachments/assets/635e25b3-2eb7-4aa2-94b5-d5ab0e4b8efa" />

### Device(s)

New 3DS, Old 3DS, Wii U, PC

### Pre-submission Checks

- [x] I have searched existing issues and confirmed this bug has not been reported before.
- [x] I have checked te known issues/roadmap and this is not a known limitation or planned fix.

**Comment by NateXS** [comment]
Fixed!

**Comment by gradylink** [comment]
Still an issue, that only fixes when loading not when being set later in the project, here's a better test project: https://files.catbox.moe/4gkb9u.sb3

**Comment by gradylink** [comment]
Maybe just add a boolean constructor to `Value` that just runs the string one with a like `bool ? "true" : "false"`?

**Comment by NateXS** [comment]
Ok now it should be fixed
