### ISSUE TITLE
crash on loading (it loading successful sometimes) [BUG]

### ISSUE THREAD

**Issue by lgor360** [NateXS/Scratch-3DS#4]
**Describe the crash or bug**
it crashes on loading. idk why...

**Scratch Projects**
[projects.zip](https://github.com/user-attachments/files/21282820/projects.zip)
(i giving u 2 versions of project. first version have "change background" blocks. second one dont have.)

**Screenshots**
![Image](https://github.com/user-attachments/assets/5bfb8f9f-7f4c-4158-bf06-a60252efa431)

**Device**
old 2ds

**Additional context**
[crash_dump_00000001.dmp](https://github.com/user-attachments/files/21282963/crash_dump_00000001.dmp)

**Comment by SowaDarek** [comment]
rename both to project.sb3 and see if it works
he said that the project is not gonna load if its not gonna be named "project" .sb3

**Comment by NateXS** [comment]
Figured out the issue with this, sometimes trying to load large images (like the 400x480 ones in this project) would make it crash. Got a fix for this though and should be good when Beta Build 3 is out :D

**Comment by NateXS** [comment]
fixed with beta build 3!

**Comment by lgor360** [comment]
> fixed with beta build 3!

yayyyyyyy thx

**Comment by lgor360** [comment]
> fixed with beta build 3!

uhhhh it not fixed completely...
sometimes it still gives dat error :c
i think it sometimes finds null or smth.

**Comment by NateXS** [comment]
dang, I'll look into it

**Comment by lgor360** [comment]
> dang, I'll look into it

wait i opened other issue... okay i will close it (new issue)
and uh just know wot i named project file to project.sb3

**Comment by NateXS** [comment]
Can you see if this is working or not in Beta 5?

**Comment by lgor360** [comment]
> Can you see if this is working or not in Beta 5?

so uh... it finding my project but still crashes..

**Comment by lgor360** [comment]
> Can you see if this is working or not in Beta 5?

i added new project.sb3 to sd card but didnt renamed it to project.sb3... menu crashed

**Comment by NateXS** [comment]
> i added new project.sb3 to sd card but didnt renamed it to project.sb3... menu crashed

what did you name it to?

**Comment by lgor360** [comment]
> > i added new project.sb3 to sd card but didnt renamed it to project.sb3... menu crashed
> 
> what did you name it to?

uhhhh...
sometest.sb3

also i renamed it to project.sb3 but it still can crash in menu

**Comment by lgor360** [comment]
hello. gud news: u fixed dat bug c:

**Comment by NateXS** [comment]
WWWWWW 

we're so back,,,,
