### ISSUE TITLE
`std::cerr` used when unzipped project isn't found

### ISSUE THREAD

**Issue by gradylink** [NateXS/Scratch-3DS#66]
This isn't really an error since it is designed to load from multiple place. This should really be using `std::cout`.

**Comment by NateXS** [comment]
fixed

**Comment by gradylink** [comment]
this is still an issue in the sdl2 version

EDIT: why won't github let me reopen the issue?

**Comment by NateXS** [comment]
fixed x2
